[package]
name = "genealogy_tree"
version = "1.0.0"
authors = []

[addresses]
genealogy_tree = "0xd61c0d45bb9379d6fa583bc659a3a36f1d8afc5b8418b2ee5a5ad93ee4a64a7e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
